-- CRIAR O BANCO DE DADOS PROJETO E ACESSAR ELE
CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE DEPARTAMENTO (
COD_DEPTO INT NOT NULL PRIMARY KEY,
NOME VARCHAR (30) NOT NULL
);

CREATE TABLE PROJETO (
COD_PROJ INT NOT NULL PRIMARY KEY,
NOME VARCHAR (30)NOT NULL,
DATAINI DATE,
DATAFIM DATE,
DURACAO INT
);

CREATE TABLE EMPREGADO (
COD_EMP INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (30) NOT NULL,
SOBRENOME VARCHAR (30) NOT NULL,
CPF CHAR (11) NOT NULL,
ENDERECO VARCHAR (100),
SALARIO FLOAT NOT NULL,
COD_DEPTO INT NOT NULL
);
-- auto incremento faz não precisar dizer o codigo do proximo empregado adicionado na tabela, ele vai sequencialmente;
-- pode ser usado apenas em chave primária e apenas 1 atributo pode ter auto incremento
ALTER TABLE EMPREGADO
auto_increment = 1000;
-- nesse caso, o primeiro empregado cadastrado será contado a partir do 1000,, o próximo 1001, etc


-- ADD A RESTRIÇÃO DE INTEGRIDADE REFERENCIAL A TABELA EMPREGADO
ALTER TABLE EMPREGADO
ADD CONSTRAINT FK_DEPTO FOREIGN KEY (COD_DEPTO) REFERENCES DEPARTAMENTO (COD_DEPTO);

CREATE TABLE TRABALHA (
COD_EMP INT NOT NULL,
COD_PROJ INT NOT NULL,
CONSTRAINT PK_TRABALHA PRIMARY KEY (COD_EMP, COD_PROJ),
CONSTRAINT FK_EMP FOREIGN KEY (COD_EMP) REFERENCES EMPREGADO (COD_EMP),
CONSTRAINT FK_PROJ FOREIGN KEY (COD_PROJ) REFERENCES PROJETO (COD_PROJ)
);
