/* SINTAXE BASICA DO SELECT 
SELECT < COLUNAS > 
FROM < TABELAS > 
WHERE < CONDIÇÕES > 
*/

-- SELECIONA TODAS AS COLUNAS DE UMA TABELA + TODAS AS LINHAS (REGISTROS)
SELECT * FROM EMPREGADO;

-- BUSCAR NA TABELA EMPREGADO O NOME E ENDEREÇO OS EMPREGADOS QUE POSSUEM SALARIO MAIOR QUE 2000
SELECT NOME, ENDERECO FROM EMPREGADO
WHERE SALARIO > 2000.00;

/* SINTAXE BASICA DO INSERT
INSERT INTO <NOME DA TABELA> 
(< NOME COLUNA1 >, <NOME COLUNA2>,...) 
VALUES (< CONSTANTE1 >, <CONSTANTE2>,...) */

-- INSERINDO DADOS NA TABELA DEPARTAMENTO
INSERT INTO departamento
    VALUES (101, 'ALPHA');

SELECT * FROM DEPARTAMENTO;

INSERT INTO departamento
	VALUES (102, 'BETA');

DESC EMPREGADO;

-- REALIZAR 5 INSERTS NA TABELA EMPREGADO, MAIS 3 NA TABELA DEPARTAMENTO E 5 PROJETOS
INSERT INTO empregado
	(NOME, SOBRENOME, CPF, ENDERECO, SALARIO, COD_DEPTO)
	VALUES ('JOSE', 'DA SILVA', '12345678910', 'AVENIDA PAULISTA, 2000', 3000.00, 101),
		   ('JOÃO', 'SOUZA', '12345678911', 'AVENIDA FARIA LIMA, 500', 5000.00, 102);
           
SELECT * FROM EMPREGADO;
           
-- AULA 04/05
-- UPDATE E DELETE
           
USE PROJETO;

SELECT * FROM EMPREGADO;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM PROJETO;
SELECT * FROM TRABALHA;


-- COMANDO UPDATE (atualização de registros) - ATUALIZA DADOS JÁ CADASTRADOS 
-- ATUALIZAR O REGISTRO DO RODOLFO ARIEL E INCLUIR O ENDEREÇO

UPDATE EMPREGADO
SET ENDEREÇO = 'RUA CASA DO ATOR, 246'
WHERE COD_EMP = 1001; -- sempre utilizar o where (questão de segurança)

UPDATE EMPREGADO 
SET ENDERECO = 'RUA CASA DO ATOR, 246'
WHERE NOME = 'GUSTAVO' AND SOBRENOME = 'ROSETTI'; 

SET SQL_SAFE_UPDATES = 0;  -- restrição de segurança "0" desligado/"1" ligado

SELECT COD_EMP FROM EMPREGADO
WHERE NOME = 'RODOLFO' AND SOBRENOME = 'ARIEL';

UPDATE EMPREGADO
SET ENDERECO = 'AVENIDA PAULISTA, 2000'
WHERE COD_EMP = 1000;

UPDATE EMPREGADO
SET ENDERECO = 'AVENIDA FARIA LIMA, 500'
WHERE COD_EMP = 1002;

UPDATE EMPREGADO
SET ENDERECO = NULL
WHERE COD_EMP = 1003;








           
           
           
           
           